# Generated by Django 5.2.7 on 2025-11-17 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Desenvolvimento', 'Desenvolvimento'), ('Teste', 'Teste'), ('Debug', 'Debug'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='ej.departamento')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos_liderados', to='ej.voluntario')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Escopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Desenvolvimento', 'Desenvolvimento'), ('Teste', 'Teste'), ('Debug', 'Debug'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos_liderados', to='ej.voluntario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'Escopo',
                'verbose_name_plural': 'Escopos',
            },
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Desenvolvimento', 'Desenvolvimento'), ('Teste', 'Teste'), ('Debug', 'Debug'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('assinantes', models.ManyToManyField(blank=True, related_name='atividades_assinadas', to='ej.voluntario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='projeto.escopo')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
