# Generated by Django 5.2.7 on 2025-11-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_escopo_fim_alter_escopo_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='projeto',
            new_name='escopo',
        ),
    ]
