# Generated by Django 5.2.7 on 2025-11-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej', '0001_initial'),
        ('projeto', '0003_rename_projeto_tarefas_escopo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='ej.voluntario'),
        ),
    ]
