# Generated by Django 5.0.7 on 2024-07-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasJuinior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('representante_legal', models.CharField(max_length=100)),
                ('cpf_representante_lega', models.CharField(max_length=11)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('site', models.URLField(blank=True)),
                ('fundacao', models.DateField()),
                ('info_contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.informacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('status_civil', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('ies', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('periodo_entrada', models.CharField(max_length=50)),
                ('periodo_saida', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DESLIGADO', 'Desativado')], default='CANDIDATO', max_length=9)),
                ('informacoes_voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.informacoes')),
                ('nome_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField()),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.funcao')),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ej.voluntario')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='voluntario_lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_departamento', to='ej.voluntario'),
        ),
        migrations.CreateModel(
            name='AnaliseDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assiduidade', models.IntegerField()),
                ('colaboracao', models.IntegerField()),
                ('tarefas', models.IntegerField()),
                ('cooperacao', models.IntegerField()),
                ('realizacao_metas', models.IntegerField()),
                ('data', models.DateField()),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='ej.voluntario')),
            ],
        ),
    ]
