# Generated by Django 5.2.7 on 2025-11-11 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autenticacao', models.CharField(max_length=12)),
                ('historico_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='ej.historicomembro')),
            ],
        ),
    ]
